name: Lost ogg

on:
  workflow_dispatch:

jobs:
  extract-and-rescue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start
        run: |
          echo "starting..."

      - name: bash
        run: |
          bash lost-ogg.sh

      - name: end
        run: |
          
          echo "ending..."

      - name: 他意があるから残す
        run: |
          echo "kkkk"



      - name: Deliver Spoils
        run: |
          git config --global user.name 'Gemini-Bot'
          git config --global user.email 'bot@gemini.team'
          git add .
          # メッセージをシンプルにしてクォート事故を防止！
          git commit -m "Mission_Update_[Skip CI]" || echo "No changes"
          git push
